server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: file-upload 